### ISSUE TITLE
Race condition exists when processing very large OAS files

### ISSUE THREAD

**Issue by doug-papenthien-by** [char0n/swagger-editor-validate#13]
**Describe the bug**
After reading the [blog post](https://swagger.io/blog/api-design/validate-openapi-definitions-swagger-editor/), I was pretty excited to integrate this into my CI/CD pipeline.  I had things up and running very quickly and the action was finding and reporting on the errors that prompted me to seek it out in the first place.

However, the next day we saw some suspicious results on a pull request that added a second OAS file to a project.  The first commit showed legit failures.  But a follow-up commit (that did not make changes to the OAS file) did not report failures.  I was not able to get it to fail again.

I'm pretty sure the issue is that the action's `hasErrors` is returning before the editor has finished rendering the errors to the DOM.  Unfortunately, I can't share the API file as it's a private API but I can say that it's about 4000 lines long, most of which are schema definitions (including some VERY large enums).  When I paste it into the editor, there's a heartbeat or two before the errors appear in the page.  I was also using the private docker method of running the action.

The errors that were not being reported were related to missing schema definitions.

**To Reproduce**
1. Setup swagger-editor-validate using the "private" method described [here](https://swagger.io/blog/api-design/validate-openapi-definitions-swagger-editor/.
2. Feed a LARGE OAS file into the action that references several missing schemas in API responses.

**Expected behavior**
Validation errors should be reliably reported.

- Version: v1.2.0.
- Platform: Ubuntu 18.04

**Comment by char0n** [comment]
@doug-papenthien-by thanks for reporting it.

I've added a 10 seconds hard waiting time before the errors are checked to give some additional time to rendering.

Use `char0n/swagger-editor-validate@master` as a workaround for now and let me know if it works for you. Meanwhile I've started looking into the problem to find out more deterministic and quicker detection of rendering being complete.

**Comment by char0n** [comment]
@doug-papenthien-by,

I didn't find better solution than 10 seconds hard limit. I've released v1.2.1 with this 10 seconds hard limit. In future if this again pops up and more then 10 seconds are going to be needed for rendering (which is highly unlikely), I make this number configurable with actions inputs.
