### ISSUE TITLE
Missing error description in v1.3.0

### ISSUE THREAD

**Issue by atoka93** [char0n/swagger-editor-validate#135]
**Describe the bug**
Using the latest version (1.3.0) I cannot see the OpenAPI specification errors, only that an error occurred:
![Screen Shot 2022-02-16 at 12 40 29 PM](https://user-images.githubusercontent.com/16056222/154248289-1fa9efb9-4c55-4614-8d42-80c66b5148e0.png)

When I pin the version to 1.2.1 it works as expected:
![Screen Shot 2022-02-16 at 12 39 53 PM](https://user-images.githubusercontent.com/16056222/154248279-1c12408a-8e8e-4456-a95e-fb97abba6149.png)

(teamfolder is the name of the repository)

**To Reproduce**
Can't share the actual specification, but I expect it's not strictly necessary.

**Expected behavior**
`@v1` (which as far as I know defaults to the latest, v1.3.0) outputs similar results to `@v1.2.1`

**Platform**
running the private use-case of the Github Action on ubuntu-latest (20.04 if I'm not mistaken)

**Thank you for your work, really useful.**

**Comment by char0n** [comment]
Thanks for the report. I'll have a look and provide a fix.

**Comment by char0n** [comment]
master is fixed. This job run verifies the fix: https://github.com/char0n/swagger-editor-validate/runs/5222812541?check_suite_focus=true

Following job will make sure that this doesn't happen in future: https://github.com/char0n/swagger-editor-validate/runs/5223146614?check_suite_focus=true

**Comment by char0n** [comment]
Fix in [v1.3.1](https://github.com/char0n/swagger-editor-validate/releases/tag/v1.3.1) and v1 tags now points to v1.3.1.
