### ISSUE TITLE
Mechanism for ignoring errors

### ISSUE THREAD

**Issue by char0n** [char0n/swagger-editor-validate#3]
**Is your feature request related to a problem? Please describe.**
It is very common that OAS definitions contains errors when validated in https://editor.swagger.io/. There are cases there is nothing that authors can do with these errors and this errors are ignored.

**Describe the solution you'd like**
Introduce an ignore mechanism ideally in form of pluggable JavaScript file which has a default export a function that asserts if error should be ignored or not.

**Describe alternatives you've considered**
Using regex in workflow file

**Additional context**
We need to document and standardize our Error object shape.

**Comment by spl** [comment]
I like this action and want to use it, but swagger-editor reports an error that I want to ignore (<https://github.com/terminusdb/openapi-specs/issues/3>). Do you have any suggestion on how to do that? Thanks!

**Comment by char0n** [comment]
Resolved by https://github.com/char0n/swagger-editor-validate/pull/126

Please see the PR how to provide a predicate to this action that determines if it should ignore error or not.

**Comment by spl** [comment]
Wonderful! Thanks! 💯
