### ISSUE TITLE
Question: how does this compare to redocly-cli

### ISSUE THREAD

**Issue by StefanLobbenmeierObjego** [char0n/swagger-editor-validate#302]
I just discovered this action, before we used https://github.com/Redocly/redocly-cli in another CI system.

I assumed this would just be a wrapper around it, but instead it looks like you parse the html for errors from openapi-editor. What are the advantages of that / what is the reason you chose that approach?

**Comment by char0n** [comment]
Hi @StefanLobbenmeierObjego,

This is basically a wrapper around https://editor.swagger.io/. The reason why this was created is that validation logic from SwaggerEditor is embedded within its code and cannot be separated into CLI (without significant effort).


You can find more answers in associated article: https://vladimirgorej.com/blog/how-to-validate-openapi-definitions-in-swagger-editor-using-github-actions/
