### ISSUE TITLE
Support `next` swagger editor (for OpenAPI 3.1)

### ISSUE THREAD

**Issue by RobinTail** [char0n/swagger-editor-validate#314]
**Is your feature request related to a problem? Please describe.**

```
Error: Error while validating in Swagger Editor
Error: TimeoutError: waiting for selector `.info .main .title` failed: timeout 30000ms exceeded
Error: Process completed with exit code 1.
```

**Describe the solution you'd like**

Support different way of error reporting in the next swagger editor: 
https://editor-next.swagger.io/

**Describe alternatives you've considered**

I haven't :)

**Additional context**

I'd like to validate the schemas against OpenAPI version 3.1 which is currently supported by the `next` generation of swagger editor. Since this action allows to specify the editor URL, I believe it would be a nice feature to support the next generation as well.
It should be not too difficult, I presume. Just lookup for another set of selectors.

What do you think?

**Comment by narthur** [comment]
For anyone who is looking for the linked issue, here's the updated URL:

https://github.com/swaggerexpert/swagger-editor-validate/issues/309

**Comment by char0n** [comment]
Thanks @narthur. Updated the link in my comment.
